name: Python CI with Poetry

on:
  push:
    branches:
      - main
      - devel
  pull_request:
    branches:
      - main
      - devel

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH


      - name: Install dependencies
        run: |
          poetry install --no-interaction --no-root --without test --with dev

      - name: Run flake8 for linting
        run:  poetry run flake8 .

      - name: Run Black for formatting check
        run:  poetry run black --check .

      - name: Run isort for import sorting check
        run:  poetry run isort --check-only .

      - name: Run pylint for static code analysis
        run:  poetry run pylint **/*.py

      - name: Run mypy for type checking
        run:  poetry run mypy .

  test:
    runs-on: ubuntu-latest
    needs: lint  # Ensure linting passes before running tests

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: |
          poetry install --no-interaction --no-root --with test --without dev

      - name: Run tests with pytest
        run: |
          poetry run pytest --maxfail=1 --disable-warnings -q

  deploy:
    runs-on: ubuntu-latest
    needs: test  # Ensure tests pass before deploying
    if: github.ref == 'refs/heads/main'  # Only deploy if pushed to 'main'

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: |
          poetry install --no-interaction --no-root

      - name: Deploy to production
        run: |
          echo "Deploying to production..."
